In [1]:
#Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its
#application.



In [2]:
#Min-Max scaling is a data preprocessing technique that transforms the values of each feature in a dataset to a range of [0, 1]. 
#This is done by subtracting the minimum value of each feature from all of its values and then dividing by the difference between the maximum and minimum values.
#Min-Max scaling is used to normalize the data so that all features have a similar scale, which can improve the performance of machine learning algorithms.

#For example, suppose we have a dataset with two features: height and weight.
#The height values in the dataset range from 150 to 200 cm, while the weight values range from 50 to 100 kg.
#Min-Max scaling would transform these values to a range of [0, 1] by subtracting the minimum value of each feature from all of its values and then dividing by the difference
#between the maximum and minimum values. So, the height values would all be between 0 and 0.5, and the weight values would all be between 0 and 0.5.

In [3]:
# Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling? Provide an example to illustrate its application.

In [6]:
#The Unit Vector technique in feature scaling involves transforming each feature to have a magnitude of 1 while preserving the direction of the original data points.
#This is achieved by dividing each data point by its magnitude.

#For example, suppose we have a dataset with two features: height and weight. The height values in the dataset range from 150 to 200 cm, 
#while the weight values range from 50 to 100 kg. Unit Vector scaling would transform these values by dividing each feature vector by its Euclidean length. 
#So, the height vector would be divided by its length of 15, and the weight vector would be divided by its length of 10. This would result in both feature vectors having a length of 1.

In [ ]:
#Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an
#example to illustrate its application.

In [5]:
#PCA (Principal Component Analysis) is a dimensionality reduction technique that transforms a high-dimensional dataset into a lower-dimensional dataset while retaining 
#as much information as possible. This is done by finding the directions of greatest variance in the data and projecting the data onto these directions.

#For example, suppose we have a dataset with 10 features, but we only care about the first two principal components. 
#PCA would transform the data into a 2-dimensional dataset by finding the directions of greatest variance in the data and projecting the data onto these directions. 
#This would result in a new dataset with only 2 features, but the first two principal components would capture most of the information in the original dataset.

In [ ]:
#Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature
#Extraction? Provide an example to illustrate this concept.

In [ ]:
#PCA (Principal Component Analysis) is a dimensionality reduction technique, while feature extraction is a process of selecting a subset of features from a 
#dataset that are most relevant to the problem at hand. PCA can be used for feature extraction by finding the principal components of the data, 
#which are the directions of greatest variance in the data. 
#The principal components can then be used to represent the data in a lower-dimensional space, while still retaining most of the information in the original data.

#For example  PCA can be used for feature extraction in a real-world application. Suppose we have a dataset of customer transactions.
#We want to use this dataset to build a model that predicts whether a customer will churn (cancel their subscription). PCA can be used to 
#find the principal components of the data, and then we can select the principal components 
#that have the strongest correlation with the churn label. This would result in a smaller subset of features that are still very informative 
#about whether a customer is likely to churn.

In [7]:
#Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset
#contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to
#preprocess the data.



In [8]:
#I would use Min-Max scaling to preprocess the data by subtracting the minimum value of each feature from all of its values and then dividing by the difference 
#between the maximum and minimum values.This would ensure that all features have a similar scale, which can improve the performance of the recommendation system.

#For example, if the price of the cheapest food item in the dataset is Rs 10 and the price of the most expensive food item is Rs 100, then Min-Max scaling would
#transform the price feature to a range of [0, 1]. This would make it easier for the recommendation system to compare the prices of different food items.

#The same process would be applied to the rating and delivery time features. This would ensure that all three features have a similar scale, which can help
#the recommendation system to make more accurate recommendations.

In [9]:
#Q6. You are working on a project to build a model to predict stock prices. The dataset contains many
#features, such as company financial data and market trends. Explain how you would use PCA to reduce the
#dimensionality of the dataset.

In [10]:
#I would use PCA to reduce the dimensionality of the dataset by finding the principal components of the data. 
#The principal components are the directions of greatest variance in the data. 
#By projecting the data onto these directions, I can reduce the dimensionality of the dataset while still retaining most of the information in the original data.

#For example, if the dataset contains 100 features, I could use PCA to reduce the dimensionality to 10 or 20 features.
#This would make it easier to train a model to predict stock prices, as the model would have to deal with fewer features.

In [11]:
# Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the
# values to a range of -1 to 1.

In [20]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

data = [1, 5, 10, 15, 20]

# Create a MinMaxScaler object
min_max = MinMaxScaler()

# Reshape the data into a column vector and then apply Min-Max scaling
scaled_data = min_max.fit_transform(np.array(data).reshape(-1, 1))

print(scaled_data)




[[0.        ]
 [0.21052632]
 [0.47368421]
 [0.73684211]
 [1.        ]]


In [21]:
#Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform
#Feature Extraction using PCA. How many principal components would you choose to retain, and why?


In [43]:
import numpy as np
import pandas as pd
from sklearn import decomposition
from sklearn.preprocessing import StandardScaler

# Create a sample dataset with 5 features
X = np.array([[170, 65, 23, 0, 120], [180, 70, 25, 1, 130], [160, 60, 21, 0, 110], [190, 80, 27, 1, 140], [175, 68, 24, 0, 125]])
df = pd.DataFrame(X, columns=['height', 'weight', 'age', 'gender', 'blood pressure'])
print(df)

# Standardize the data
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

# Perform feature extraction using PCA with n_components=4
pca = decomposition.PCA(n_components=4)
X_std_pca = pca.fit_transform(X_std)
print(X_std_pca.shape)
print(X_std_pca)

# Print the explained variance ratio of each component
print(pca.explained_variance_ratio_)



   height  weight  age  gender  blood pressure
0     170      65   23       0             120
1     180      70   25       1             130
2     160      60   21       0             110
3     190      80   27       1             140
4     175      68   24       0             125
(5, 4)
[[-1.26381517e+00 -3.33139420e-01 -6.38471170e-02  2.24721638e-17]
 [ 1.27748549e+00  7.89708122e-01 -1.97737035e-01  9.47862762e-18]
 [-2.98374459e+00  4.09295002e-01  1.82910655e-01  6.87992039e-18]
 [ 3.33969656e+00 -1.42527003e-01  2.01318200e-01  1.12110991e-17]
 [-3.69622293e-01 -7.23336701e-01 -1.22644702e-01  1.68250591e-18]]
[9.36884938e-01 5.78269248e-02 5.28813751e-03 3.08278161e-35]


In [ ]:
The variance of each component is as follows:

Component 1: 0.936884938
Component 2: 0.0578269248
Component 3: 0.00528813751
Component 4: close to Zero

I chose to retain the first three principal components because they capture 95.8% of the variance in the data. 
This means that the first three principal components contain most of the information in the original data.
Retaining more principal components would not significantly improve the representation of the data,
but it would also increase the computational complexity.